### ISSUE TITLE
add some more expressions like on add order, on deposit, on withdraw etc.

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#170]

**Comment by thedavidmeister** [comment]
this idea was originally "hook style" but after thinking about it more, and based on my past experiences working with hook based systems in web 2 etc., hooks tend not to compose very well in practise

a more direct approach where a list of expressions to run can be passed to each function call, which are all run inline with that specific function call and never again allows and requires the caller to handle any ambiguities in how/when the additional logic should be called

the caller as a smart contract may well implement a "hooks" system on top of direct lists of expressions, but the inverse is not true

**Comment by hardyjosh** [comment]
@thedavidmeister is this resolved now with Actions in v4?

**Comment by thedavidmeister** [comment]
@hardyjosh yeah
