### ISSUE TITLE
Tauri app not launching on mac os

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#224]
Upon opening the tauri app on mac os, it immediately crashes with the following debug message:

```
thedavidmeister@davids-iMac MacOS % ./rain-orderbook-tauri-app 
dyld[3986]: Library not loaded: /nix/store/240qrs8li8w6zbl9khgikzjvi2ynsm5a-gettext-0.21.1/lib/libintl.8.dylib
  Referenced from: <5B83F8D2-96C6-3924-8301-930C9724B55E> /Applications/rain-orderbook-tauri-app.app/Contents/MacOS/rain-orderbook-tauri-app
  Reason: tried: '/nix/store/240qrs8li8w6zbl9khgikzjvi2ynsm5a-gettext-0.21.1/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/nix/store/240qrs8li8w6zbl9khgikzjvi2ynsm5a-gettext-0.21.1/lib/libintl.8.dylib' (no such file), '/nix/store/240qrs8li8w6zbl9khgikzjvi2ynsm5a-gettext-0.21.1/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
zsh: abort      ./rain-orderbook-tauri-app
```

**Comment by mattyg** [comment]
- I created a minimal tauri app with a matching tauri.conf.json to reproduce the issue -- was able to reproduce the issue by adding the change made in #219 -- removing it resolved the issue
- The original issue, where the app silently fails to launch may be related to building binary on x86_64, then running on aarch64 (https://github.com/tauri-apps/tauri/issues/8763), with ad-hoc signing
-  One solution may be to build separate binaries on both x86_64 github runners (macos-latest) and new beta arm runners (macos-14)
- I've tried building univeral fat binaries with `cargo tauri build --target universal-apple-darwin` which works on an aarch host, but doesn't work from the rainix tauri-shell on that host -- even when adding the additional cargo targets. Would need to dig in more to figure out why. 

- Also when running that universal binary on a much older x86_64 mac (10.14), the app launches but the screen is blank (possible related to this: https://github.com/tauri-apps/tauri/issues/8592#issuecomment-1891822500)

**Comment by mattyg** [comment]
I'm attempting to deub the builds on an x86-64 mac running mac os 14:
I'm not able to run the foundry nixpkg due to this issue: https://github.com/shazow/foundry.nix/issues/23

**Comment by mattyg** [comment]
I was able to build a demo tauri app in nix that runs properly on x86_64 mac by using this flake: https://github.com/tauri-apps/tauri/issues/6612#issuecomment-1497231290

Will need to compare to our flake and see what we're missing

**Comment by mattyg** [comment]
I added nix pkgs   libiconv and gettext to the rainix flake -- building on ci for mac x86 still not working -- however I was able to build a demo app on a mac x86 vps using the rainix flake

**Comment by mattyg** [comment]
Some users on aarch64 macs are still having the same issue. Will try comparing builds on the host and builds in nix -- see if `ldd` shows them as expecting different dynamic libraries

**Comment by mattyg** [comment]
This is resolved -- see the `ob-tauri-before-build` nix script for how we bundle linked libraries and then update the binary to use them.

**Comment by thewh1teagle** [comment]
I experience the same issue - I compile [app](https://github.com/thewh1teagle/vibe) for macOS aarch64,
when not configuring signing, it opens macOS error with [app-is-damaged-and-cant-be-opened](https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/)
When signing with ad-hoc identity (`tauri.macos.conf.json -> bundle.macOS.signingIdentity: "-"`) if crash with 
```console
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libavcodec.60.dylib
Referenced from: <D007FD2C-8AD0-336A-944D-C186621D1CEF> /Volumes/VOLUME/vibe.app/Contents/MacOS/vibe
Reason: tried: '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' (code signature in <BEFA8967-6321-3361-9151-FF5EE424F751> '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' (code signature in <BEFA8967-6321-3361-9151-FF5EE424F751> '/Volumes/vibe/vibe.app/Contents/Frameworks/libavcodec.60.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
(terminated at launch; ignore backtrace)
```

Can you describe how you managed to fix it?
