### ISSUE TITLE
Indicator that an order is "active" on the vaults list

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#278]
- give them a green background, green outline, or prefix with a green bubble, to indicate the order is active
- sort so that active orders show up first

![Image](https://github.com/rainlanguage/rain.orderbook/assets/159270/3f36019d-551b-4018-9688-aba24964662c)

**Comment by hardyjosh** [comment]
we already have a convention for this on the order detail page so we just need to bring that across

![Image](https://github.com/user-attachments/assets/f9130799-29c6-499a-82cd-1c588b198069)
