### ISSUE TITLE
Make deposit form styling more consistent

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#333]
Not really sure what's happening here exactly, needs more investigation.

https://github.com/rainlanguage/rain.orderbook/assets/1190022/a9f0fc59-e084-4323-bb32-38f2244537d2

**Comment by hardyjosh** [comment]
@mattyg is the only reason we're not using the Input component because you need to use an action?

Looks like https://github.com/themesberg/flowbite-svelte/issues/1235 would resolve that

**Comment by mattyg** [comment]
Yeah I think that's right

**Comment by mattyg** [comment]
nevermind they just need `type="text"` on the input element
