### ISSUE TITLE
Non-dismissable subgraph toast error

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#338]
This error comes up from time to time, doesn't go away on its own and isn't dismissable

![Image](https://github.com/rainlanguage/rain.orderbook/assets/1190022/7a5eeb0b-13d0-43f9-8510-001d63520180)

**Comment by mattyg** [comment]
I believe the toast is dismissable, but the close button is covered by the text overflowing its container, likely due to the url not being split mid word. Styling should be adjusted to avoid this and ensure close button is always visible.
