### ISSUE TITLE
fix order input/ouput matching network

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/rain.orderbook#379]

**Comment by mattyg** [comment]
Can you explain the issue more? I want to understand it review the pr @rouzwelt

**Comment by rouzwelt** [comment]
> Can you explain the issue more? I want to understand it review the pr @rouzwelt 

it is already fixed in the attached PR, which is to make sure the tokens network match tge orser network

**Comment by mattyg** [comment]
yeah I'm reviewing the pr and just wanted to make sure I understood the issue -- got it thanks

**Comment by rouzwelt** [comment]
> yeah I'm reviewing the pr and just wanted to make sure I understood the issue -- got it thanks

sorry this PR is for this issue #380

**Comment by rouzwelt** [comment]
I just attached #380  to this issue
