### ISSUE TITLE
Version number bumping and display in app

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#406]
We started this discussion in denver but I don't remember if we came to a clear resolution.

It would be helpful to have a version number displayed in the app, so the we can clearly check if a user is on the latest version or prompt them to upgrade.

However its not clear the best way to accomplish that, given that we're generating releases manually just renamed by their commit hash.

We could potentially inject the commit hash into the app at build-time, so that can be displayed, but it would be more helpful to know if a build is "older" or "newer" rather than a hash with no clear ordering.

One option is to manually bump version numbers for the tauri app, then publish the first release of a version number to the website, and display both the version number and commit hash in the app.

**Comment by hardyjosh** [comment]
@thedavidmeister what are your thoughts on this? I feel like a hash would still be useful, we could at least ascertain which version someone was using, even if that just means we know it isn't the latest.

**Comment by thedavidmeister** [comment]
@hardyjosh hash would be very useful, there isa ctually already a version visible in the app if you go to "about" but it isn't that helpful

<img width="282" alt="Screenshot 2024-05-21 at 14 58 05" src="https://github.com/rainlanguage/rain.orderbook/assets/629710/dda5534c-3a6b-44f5-ae2e-5bb06d032fb0">

**Comment by hardyjosh** [comment]
would also be good if the cli reported its own commit hash

**Comment by hardyjosh** [comment]
This is resolved now by https://github.com/rainlanguage/rain.orderbook/pull/801
