### ISSUE TITLE
`FooString` e.g. `NetworkString` is now a misnomer

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#425]
as per https://github.com/rainlanguage/rain.orderbook/pull/374 `NetworkString` is no longer stringly typed, so the name is bad

**Comment by mattyg** [comment]
my preference is to rename FooString -> FooConfig, and rename FooConfig -> FooConfigExtended (i.e. FooConfigExtended is the same data as FooConfig, just with the foreign keys filled out)
