### ISSUE TITLE
default colours are illegibile in night mode for chart

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#459]
![telegram-cloud-photo-size-2-5463387254975222933-y](https://github.com/rainlanguage/rain.orderbook/assets/629710/399413f5-6439-48e0-8423-ad4d2c46d7c6)

**Comment by rouzwelt** [comment]
example:
![Image](https://github.com/rainlanguage/rain.orderbook/assets/98348398/e338a565-4004-491c-a621-974a21011451)
