### ISSUE TITLE
vaults can have a non zero balance (due to trading) and show "no deposits or withdrawals"

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#569]
<img width="1009" alt="Screenshot 2024-04-06 at 16 53 44" src="https://github.com/rainlanguage/rain.orderbook/assets/629710/1dd7cf78-3cab-4a53-9970-8bb25b9813ab">

**Comment by hardyjosh** [comment]
This will be resolved by https://github.com/rainlanguage/rain.orderbook/pull/697
