### ISSUE TITLE
Bug: Order -> Trades Table has BigInt Syntax error when coercing unexpected float

### ISSUE THREAD

**Issue by danalexilewis** [rainlanguage/rain.orderbook#607]
Loom Video
https://www.loom.com/share/bd837ae8d3574268ba2975feb797383c?sid=7ba23f67-ecf9-404e-935f-a9855e48f67a

![Image](https://github.com/rainlanguage/rain.orderbook/assets/1431991/fc49b3fb-e59d-4f64-ba93-66b0772364a0)

TLDR We have some sort of type error happening upstream from the Front end.

At present the BigInt function we are using expects either as a BigInt as a json numeric value or a string in the constructor. If we give it a float as string it throws an error.

We can add some error handling code to the front end and thereby allow the table to render instead of crashing the app. We would need to decide what to show instead to the user.

But ultimately we need to fix this upstream and settle on if the `input_display` and `output_display` are also `BigInt` or are `Floats`. If both are acceptable we will need a better write up of how to handle the math of it.

**Comment by hardyjosh** [comment]
This was happening because input_display is the token amount adjusted with decimals, so it includes a decimal part. `BigInt`'s must be integers.

Fixed for now by changing to `Number` instead.
