### ISSUE TITLE
Make subtitle font size on charts smaller than the title

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#656]
## Motivation

At the moment our titles and subtitles for charts are the same size. This doesn't look that great.

![Image](https://github.com/rainlanguage/rain.orderbook/assets/1190022/ee743d72-0f10-4c0e-8184-34636f704bc4)

## Solution

Make the subtitles a smaller font size.

**Comment by rouzwelt** [comment]
made subtitle smaller:


![Image](https://github.com/rainlanguage/rain.orderbook/assets/98348398/9fa02dc4-dc2c-4579-af82-33491259a64c)
