### ISSUE TITLE
Documenting foundry logs extracted data.

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.orderbook#677]
Need to document logs generated in the foundry script present in [PR 645](https://github.com/rainlanguage/rain.orderbook/pull/645), so that anybody could inspect why a transaction with the particular calldata isn't clearing.
- The process needs to documented so that even a non-technical person can follow and inspect the logs, extract the relevant data and infer why a transaction isn't clearing.  
- Potentially could be a setup in codespace with nix installed so that anybody can access it via browser without having to have the foundry setup on local machine.

**Comment by thedavidmeister** [comment]
this is not what i asked for, i just want a dotpoint of what @rouzwelt did already
