### ISSUE TITLE
Context for LibOrderBook.doPost 

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.orderbook#750]
- Currently `LibOrderBook.doPost` call has empty context, need context values accessible for post add order sources.
```
/* Order hash value should be accessible from context*/
#post-add-order 
   _: ...
   :set(hash(order-hash() "key") 1);
```

**Comment by Siddharth2207** [comment]
Resolved, but only `order-hash` , `order-owner` is available in the context

**Comment by thedavidmeister** [comment]
@Siddharth2207 it's not clear to me what else you're looking for, adding an order isn't a live trade so what else should be in context in your opinion?

**Comment by thedavidmeister** [comment]
there's no order context so closing this out
