### ISSUE TITLE
Deploymnet CI for flare is not working

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.orderbook#770]
- Deployment CI for raindex contracts is not working. Issue potentially due to bumped `evm_version = "cancun"`.
https://github.com/rainlanguage/rain.orderbook/actions/runs/10383644556/job/28748984611

**Comment by thedavidmeister** [comment]
@Siddharth2207 afaik, this was fixed, please confirm?

**Comment by Siddharth2207** [comment]
yeah its resolved
