### ISSUE TITLE
`clear2()` 0 order ratio bug

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/rain.orderbook#783]
There seems to be a bug in an edge with `clear2()` where if Alice or Bob order ratio is 0, then the tx goes through silently without any reverts or issues, but nothing actually clears, no vault balance changes and no bounties.

This should not happen, in fact if the order ratio is 0, that measn all the output vault should go to the tx sender as bounty.

**Comment by thedavidmeister** [comment]
i've assigned to @ninokeldishvili just to write a test for this, then i'll work on a fix
