### ISSUE TITLE
the quote table disappears while it is refreshing

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#798]
<img width="1167" alt="Screenshot 2024-08-27 at 18 48 08" src="https://github.com/user-attachments/assets/54bd4365-f8b8-40ac-b3b5-967e4ed6d09e">

this is very annoying as it pops up every few seconds, making the table hard to read

**Comment by hardyjosh** [comment]
Fixed by https://github.com/rainlanguage/rain.orderbook/pull/807
