### ISSUE TITLE
Hard-coding default RPC urls?

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#80]
Do we want to hard-code some default RPC urls for the different chains that rain.orderbook plans to support? Either commonly used free RPCs or else paid RPC under rain's billing account?

This would reduce the friction for users to get setup in using the tools.

I could start with the default free rpc urls used by foundry. @hardyjosh @thedavidmeister

**Comment by thedavidmeister** [comment]
@hardyjosh @mattyg hmm i'd rather not

the free ones i find flakey for submitting transactions and i don't think it's a good idea to put our API key or anything that we pay for in these binaries

is it really such an issue for users to provide an rpc? we can send them to https://chainlist.org/ for example

**Comment by thedavidmeister** [comment]
@mattyg from what i've seen in the past, when you bake a key in it runs out almost instantly, because it's the same key shared by everyone, and then it's even more confusing than doing nothing

we could also provide some links to infura and alchemy etc.

**Comment by mattyg** [comment]
yeah makes sense -- that sounds good we'll just have to document it well
