### ISSUE TITLE
can't deposit

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#865]
![IMAGE 2024-09-15 17:57:26](https://github.com/user-attachments/assets/99e88751-e2b3-432d-b8da-b7c09f24e094)

button greyed out

no error displayed

no idea what to do to fix it

**Comment by hardyjosh** [comment]
@findolor when you fix this one can you also pls put up a test for `InputTokenAmount.svelte`? There's a chance this bug would've been picked up straight away if we'd had a test for the component behaviour already.
