### ISSUE TITLE
Defi llama integration

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#915]

**Comment by thedavidmeister** [comment]
https://medium.com/timeswap/defillama-integration-timeswap-e591254824e4

**Comment by thedavidmeister** [comment]
https://docs.llama.fi/list-your-project/submit-a-project

**Comment by dcatki** [comment]
@rouzwelt isnt this done?

**Comment by rouzwelt** [comment]
> @rouzwelt isnt this done?

yes it is
